dist: xenial
language: python
python: '3.7'
services: docker
script: python manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_45f3547f7754_key -iv $encrypted_45f3547f7754_iv
  -in ./mysite/my_credentials.py.enc -out ./mysite/my_credentials.py -d