dist: xenial
language: python
python: '3.7'
services: docker
script: python manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_8120aa661d02_key -iv $encrypted_8120aa661d02_iv
  -in mysite/my_credentials.py.enc -out mysite/my_credentials.py -d
